//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class libros
    {
        [Display(Name = "#")]
        public int id { get; set; }
        [Display(Name = " Libro")]
        public string nombre_libro { get; set; }
        [Display(Name = "Categoria")]
        public string nombre_categoria { get; set; }
        [Display(Name = "Fecha de lanzamiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime fecha { get; set; }
        

    }
}
